# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: BUILD & CHECK

# on:
#  push:
#    branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        r-version: ['4.3.0']

    steps:
      - uses: actions/checkout@v3
      - name: Install Linux Libraries
        run: |
          sudo apt-get update
          sudo apt-get install texlive
          sudo apt-get install -y libz-dev \
            nano \
            librsvg2-dev \
            libcurl4-openssl-dev \
            libssl-dev \
            libxml2-dev \
            libssh2-1-dev \
            libgdal-dev \
            libproj-dev \
            libgeos-dev \
            libglu1-mesa-dev \
            libgmp3-dev \
            libmpfr-dev \
            libgl-dev \
            libglpk-dev \
            libharfbuzz-dev \
            libfribidi-dev \
            libmagick++-dev \
            pandoc
          sudo apt-get install -y qpdf \
            ghostscript-x \
            default-jre \
            default-jdk
          R CMD javareconf -e
    
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@v2.6.5
        with:
          r-version: ${{ matrix.r-version }}
          
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "devtools"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
        
      - name: Check
        run: devtools::check()
        shell: Rscript {0}
